import type { DemoStep } from './demoTypes';
// Presentation copy references canonical IDs; domain statements and timestamps stay in their catalogs.
export const demoStory: readonly DemoStep[] = [
  {
    id: 'concept',
    chapterId: 'understand',
    route: '/',
    title: 'Conversation → governed working proof',
    narration:
      'Convo2POC turns client conversations into governed, traceable working prototypes.',
    durationMs: 8000,
    condition: 'ready',
    spotlight: 'overview-concept',
  },
  {
    id: 'signals',
    chapterId: 'understand',
    route: '/session',
    title: 'Detect requirements as the client speaks',
    narration:
      'The conversation becomes requirements, actors and business-rule signals—not just a transcript.',
    durationMs: 14000,
    condition: 'requirements',
    spotlight: 'session-requirement-detection',
    simulation: {
      lane: 'session',
      until: 'requirements',
      presentationMs: 10000,
    },
  },
  {
    id: 'ambiguity',
    chapterId: 'understand',
    route: '/session',
    title: 'Surface uncertainty',
    narration:
      'Instead of guessing what an undefined priority means, Convo2POC flags it for clarification.',
    durationMs: 8000,
    condition: 'ambiguity',
    spotlight: 'session-ambiguity',
    simulation: { lane: 'session', until: 'ambiguity', presentationMs: 4000 },
  },
  {
    id: 'client-answer',
    chapterId: 'understand',
    route: '/session',
    title: 'Capture the client’s answer',
    narration:
      'Client evidence supplies the priority definition. Formal consultant review remains a separate step.',
    durationMs: 8000,
    condition: 'answer',
    spotlight: 'session-ambiguity',
    simulation: { lane: 'session', until: 'answer', presentationMs: 4000 },
  },
  {
    id: 'discovery-complete',
    chapterId: 'understand',
    route: '/session',
    title: 'Complete the discovery evidence',
    narration:
      'The remaining conversation completes the workflow, scope boundaries and source evidence.',
    durationMs: 10000,
    condition: 'session-complete',
    spotlight: 'session-requirement-detection',
    simulation: { lane: 'session', until: 'complete', presentationMs: 8000 },
  },
  {
    id: 'clarification-evidence',
    chapterId: 'clarify',
    route: '/clarifications?selected=OQ-001',
    title: 'Resolve ambiguity with evidence',
    narration:
      'The original statement, missing definition, suggested question and recorded answer remain reviewable.',
    durationMs: 9000,
    condition: 'session-complete',
    spotlight: 'clarification-oq001',
  },
  {
    id: 'confirm-priority',
    chapterId: 'clarify',
    route: '/clarifications?selected=OQ-001',
    title: 'Consultant confirms the priority rule',
    narration:
      'Client evidence becomes a governed requirement update only after consultant confirmation.',
    durationMs: 7000,
    condition: 'oq001-confirmed',
    spotlight: 'clarification-oq001',
    action: { type: 'clarification', ids: ['OQ-001'] },
    governance: {
      type: 'clarification-approval',
      label: 'Priority clarification reviewed',
    },
  },
  {
    id: 'confirm-other-evidence',
    chapterId: 'clarify',
    route: '/clarifications?selected=OQ-002',
    title: 'Review remaining clarification evidence',
    narration:
      'Role and scope answers are reviewed through the same consultant-controlled process.',
    durationMs: 7000,
    condition: 'clarifications-confirmed',
    spotlight: 'clarification-oq001',
    action: { type: 'clarification', ids: ['OQ-002', 'OQ-003'] },
    governance: {
      type: 'clarification-approval',
      label: 'Remaining client evidence reviewed',
    },
  },
  {
    id: 'structured-model',
    chapterId: 'structure',
    route: '/requirements?selected=FR-007',
    title: 'Inspect the structured requirement model',
    narration:
      'Requirements have types, confidence, source evidence and relationships. Uncertainty and assumptions remain explicit.',
    durationMs: 14000,
    condition: 'clarifications-confirmed',
    spotlight: 'requirement-fr007',
    action: { type: 'select-requirement', id: 'FR-007' },
  },
  {
    id: 'scope-boundary',
    chapterId: 'scope',
    route: '/scope',
    title: 'Reduce the full vision to a focused POC',
    narration:
      'Core capabilities are included, dependencies simulated, and production capabilities deferred with reasons.',
    durationMs: 10000,
    condition: 'clarifications-confirmed',
    spotlight: 'scope-funnel',
  },
  {
    id: 'success-contract',
    chapterId: 'scope',
    route: '/scope',
    title: 'Define the demonstration contract',
    narration:
      'Success criteria define what the prototype must prove. Scope reduction is deliberate and traceable.',
    durationMs: 7000,
    condition: 'ready',
    spotlight: 'scope-success',
  },
  {
    id: 'scope-governance',
    chapterId: 'scope',
    route: '/scope',
    title: 'Consultant approves the POC boundary',
    narration:
      'The consultant reviews requirements, assumptions, scope and success criteria before creating the baseline.',
    durationMs: 7000,
    condition: 'rb001',
    spotlight: 'scope-approval',
    action: { type: 'approve-scope' },
    governance: {
      type: 'scope-approval',
      label: 'POC scope and success criteria reviewed',
    },
  },
  {
    id: 'baseline-locked',
    chapterId: 'scope',
    route: '/scope',
    title: 'RB-001 is locked',
    narration:
      'The approved scope becomes the versioned implementation contract. Later changes require a new baseline.',
    durationMs: 4000,
    condition: 'rb001',
    spotlight: 'scope-approval',
  },
  {
    id: 'engineering-contract',
    chapterId: 'generate',
    route: '/generation',
    title: 'Engineer from the approved baseline',
    narration:
      'Requirement and architecture responsibilities consume the locked baseline rather than raw meeting text.',
    durationMs: 10000,
    condition: 'rb001',
    spotlight: 'generation-baseline',
    simulation: {
      lane: 'generation',
      until: 'architecture',
      presentationMs: 7000,
    },
  },
  {
    id: 'parallel-engineering',
    chapterId: 'generate',
    route: '/generation',
    title: 'UI · Backend · Data in parallel',
    narration:
      'Specialized engineering responsibilities progress in parallel against the same approved contract.',
    durationMs: 13000,
    condition: 'parallel',
    spotlight: 'generation-parallel',
    simulation: { lane: 'generation', until: 'parallel', presentationMs: 5000 },
  },
  {
    id: 'test-contract',
    chapterId: 'generate',
    route: '/generation',
    title: 'Validate requirements and success criteria',
    narration:
      'Canonical tests validate the workflow, role rules and dedicated feature contracts.',
    durationMs: 10000,
    condition: 'rb001',
    spotlight: 'generation-tests',
    simulation: { lane: 'generation', until: 'tests', presentationMs: 7000 },
  },
  {
    id: 'security-sandbox',
    chapterId: 'generate',
    route: '/generation',
    title: 'Validate and prepare the review sandbox',
    narration:
      'Build, security and sandbox checks complete before the working POC becomes reviewable.',
    durationMs: 8000,
    condition: 'generation-complete',
    spotlight: 'generation-sandbox',
    simulation: { lane: 'generation', until: 'complete', presentationMs: 6000 },
  },
  {
    id: 'review-ready',
    chapterId: 'generate',
    route: '/generation',
    title: 'POC ready for human review',
    narration:
      'Validation is complete. A consultant now demonstrates and reviews the working prototype.',
    durationMs: 4000,
    condition: 'generation-complete',
    spotlight: 'generation-baseline',
  },
  {
    id: 'employee-p1',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Employee creates a P1 request',
    narration:
      'The working application creates a request and exposes the manager approval requirement.',
    durationMs: 7000,
    condition: 'p1-created',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-create' },
  },
  {
    id: 'administrator-assignment',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Administrator assigns an engineer',
    narration:
      'Assignment follows the reviewed role rule. The request keeps its approval requirement.',
    durationMs: 6000,
    condition: 'p1-assigned',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-assign' },
  },
  {
    id: 'engineer-guard',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Work is blocked before approval',
    narration:
      'The assigned engineer cannot begin P1 work until a manager approves it. The runtime enforces the rule.',
    durationMs: 5000,
    condition: 'p1-blocked',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-blocked' },
  },
  {
    id: 'manager-approval',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Manager approves the request',
    narration:
      'Manager approval releases the workflow and records the decision in request history.',
    durationMs: 7000,
    condition: 'p1-approved',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-approve' },
  },
  {
    id: 'engineer-progress',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Engineer progresses the approved request',
    narration:
      'The assigned engineer can now move the request into progress through the existing guarded transition.',
    durationMs: 6000,
    condition: 'p1-progressed',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-progress' },
  },
  {
    id: 'working-history',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Inspect the recorded workflow history',
    narration:
      'Creation, assignment, approval and status changes remain visible as deterministic evidence.',
    durationMs: 4000,
    condition: 'p1-progressed',
    spotlight: 'preview-p1-approval',
    action: { type: 'p1-history' },
  },
  {
    id: 'feature-lineage',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Why this feature exists',
    narration:
      'The generated feature remains connected to requirements, clarification, client statements, scope, artifacts and tests.',
    durationMs: 8000,
    condition: 'p1-progressed',
    spotlight: 'preview-feature-evidence',
    action: { type: 'feature-evidence' },
  },
  {
    id: 'v1-consultant-review',
    spotlight: 'preview-review',
    chapterId: 'validate',
    route: '/preview?version=v1',
    title: 'Consultant approves the client demonstration',
    narration:
      'The consultant reviews the working workflow, scope, success criteria, limitations and demonstration content.',
    durationMs: 7000,
    condition: 'v1-approved',
    action: { type: 'approve-v1' },
    governance: {
      type: 'poc-review',
      label: 'POC v1 reviewed for client demonstration',
    },
  },
  {
    id: 'intent-to-test',
    chapterId: 'trace',
    route: '/traceability?feature=approval&selected=requirement%3AFR-007',
    title: 'Follow the complete P1 evidence chain',
    narration:
      'Client intent remains connected through clarification, scope, implementation, the working feature and validation.',
    durationMs: 16000,
    condition: 'trace-complete',
    spotlight: 'trace-p1-path',
    action: { type: 'trace-p1' },
  },
  {
    id: 'client-change',
    chapterId: 'evolve',
    route: '/feedback',
    title: 'Capture a new client request',
    narration:
      'Feedback becomes a controlled change request against the existing approved baseline.',
    durationMs: 8000,
    condition: 'cr001',
    spotlight: 'feedback-cr001',
    simulation: { lane: 'feedback', until: 'cr001', presentationMs: 6000 },
  },
  {
    id: 'analyze-change',
    chapterId: 'evolve',
    route: '/feedback',
    title: 'Analyze the approval policy delta',
    narration:
      'Requirement and success-criterion revisions remain separate from the preserved v1 baseline.',
    durationMs: 12000,
    condition: 'feedback-analyzed',
    spotlight: 'feedback-cr001',
    simulation: { lane: 'feedback', until: 'complete', presentationMs: 8000 },
  },
  {
    id: 'reuse-boundary',
    chapterId: 'evolve',
    route: '/feedback',
    title: 'Inspect affected and reusable assets',
    narration:
      'Only the policy consumers and relevant validation assets change. Architecture and scope categories remain intact.',
    durationMs: 10000,
    condition: 'feedback-analyzed',
    spotlight: 'feedback-impact',
  },
  {
    id: 'change-governance',
    chapterId: 'evolve',
    route: '/feedback',
    title: 'Consultant approves CR-001',
    narration:
      'The consultant reviews client evidence and the full impact before creating RB-002.',
    durationMs: 7000,
    condition: 'rb002',
    spotlight: 'feedback-rb002',
    action: { type: 'approve-change' },
    governance: {
      type: 'change-approval',
      label: 'Client change and impact reviewed',
    },
  },
  {
    id: 'targeted-regeneration',
    chapterId: 'evolve',
    route: '/feedback',
    title: 'Regenerate the changed policy path',
    narration:
      'Targeted regeneration reuses unaffected assets and preserves historical v1 test evidence.',
    durationMs: 28000,
    condition: 'v2-ready',
    spotlight: 'feedback-delta',
    simulation: { lane: 'delta', until: 'complete', presentationMs: 25000 },
  },
  {
    id: 'preserved-v1',
    chapterId: 'evolve',
    route: '/preview?version=v1',
    title: 'POC v1 retains its original P2 behavior',
    narration:
      'The original POC is preserved. P2 requests still require no manager approval in v1.',
    durationMs: 10000,
    condition: 'v1-p2',
    spotlight: 'preview-v1-p2',
    action: { type: 'p2-v1' },
  },
  {
    id: 'changed-v2',
    chapterId: 'evolve',
    route: '/preview?version=v2',
    title: 'POC v2 demonstrates the changed P2 rule',
    narration:
      'RB-002 produces a traceable v2 where P2 requests require manager approval before work begins.',
    durationMs: 12000,
    condition: 'v2-p2',
    spotlight: 'preview-v2-p2',
    action: { type: 'p2-v2' },
  },
  {
    id: 'complete',
    chapterId: 'outcome',
    route: '/preview?version=v2',
    title: 'Convo2POC demo complete',
    narration:
      'Conversation became governed working proof, and client feedback became a controlled versioned change.',
    durationMs: 0,
    condition: 'v2-ready',
    completion: true,
  },
];
export const fullDemoDurationMs = demoStory.reduce(
  (sum, step) => sum + step.durationMs,
  0,
);
