import { Link } from 'react-router-dom';
import { useDemoStore } from '@/store/demoStore';
import { selectAgentContract } from '@/store/generationSelectors';
import { getBaselineArtifacts } from '@/data/generation';
import { generationEvents } from '@/simulation/generationEvents';
import { formatGenerationTime } from '@/simulation/generationEngine';
import { AgentStateBadge } from './AgentOrchestrationGraph';
export function AgentInspector() {
  const state = useDemoStore();
  const agent = selectAgentContract(state, state.generation.selectedAgentId);
  const artifacts = state.pocBaseline
    ? getBaselineArtifacts(state.pocBaseline)
    : [];
  const selected = artifacts.find(
    (a) => a.id === state.generation.selectedArtifactId,
  );
  const activity = generationEvents
    .filter(
      (e) =>
        'agentId' in e &&
        e.agentId === agent.id &&
        state.generation.visibleEventIds.includes(e.id),
    )
    .slice(-3);
  return (
    <aside
      className="gen-panel gen-inspector"
      aria-label={selected ? 'Artifact inspector' : 'Agent inspector'}
    >
      <header>
        <div>
          <span className="gen-kicker">
            {selected
              ? 'Traceable output metadata'
              : 'Inspect engineering responsibility'}
          </span>
          <h2>{selected ? selected.path.split('/').at(-1) : agent.name}</h2>
        </div>
      </header>
      {selected ? (
        <>
          <div className="gen-inspector-body">
            <p>{selected.label}</p>
            <dl>
              <dt>Generated by</dt>
              <dd>
                {
                  state.agentStatuses.find((a) => a.id === selected.generatedBy)
                    ?.name
                }
              </dd>
              <dt>Baseline</dt>
              <dd>RB-001 · locked input</dd>
              <dt>Status</dt>
              <dd>{state.generation.artifactStatuses[selected.id]}</dd>
              <dt>Path</dt>
              <dd>
                <code>{selected.path}</code>
              </dd>
            </dl>
            <p className="gen-note">
              Simulated metadata preview · no source files created
            </p>
            <h3>Requirement sources</h3>
            <RequirementLinks ids={selected.requirementIds} />
            {selected.successCriterionIds.length > 0 && (
              <p>
                Success criteria: {selected.successCriterionIds.join(' · ')}
              </p>
            )}
            <button
              className="gen-text-button"
              onClick={() => state.selectGenerationArtifact(null)}
            >
              Return to agent inspector
            </button>
          </div>
        </>
      ) : (
        <div className="gen-inspector-body">
          <p>{agent.description}</p>
          <AgentStateBadge status={agent.status} />
          <div className="gen-inspector-progress">
            <strong>{agent.progress}%</strong>
            <progress
              max={100}
              value={agent.progress}
              aria-label={`${agent.name} inspector progress`}
            />
          </div>
          <h3>Approved inputs</h3>
          <Link to="/scope">RB-001 · View locked baseline ↗</Link>
          <ul className="gen-compact-list">
            {agent.inputArtifactIds.map((id) => (
              <li key={id}>
                {artifacts
                  .find((a) => a.id === id)
                  ?.path.split('/')
                  .at(-1)}
              </li>
            ))}
          </ul>
          <h3>Output contract</h3>
          <ul className="gen-output-list">
            {agent.outputArtifactIds.map((id) => {
              const a = artifacts.find((a) => a.id === id)!;
              return (
                <li key={id}>
                  <span>{a.label}</span>
                  <small>
                    {state.generation.artifactStatuses[id] ?? 'Planned'}
                  </small>
                </li>
              );
            })}
          </ul>
          <h3>Requirements affected</h3>
          <RequirementLinks ids={agent.requirementIds} />
          {agent.requirementIds.includes('FR-007') && (
            <Link
              className="gen-text-button"
              to="/clarifications?selected=OQ-001"
            >
              View priority clarification ↗
            </Link>
          )}
          <h3>Activity</h3>
          {activity.length ? (
            <ul className="gen-compact-list">
              {activity.map((e) => (
                <li key={e.id}>
                  <code>{formatGenerationTime(e.at)}</code> {e.message}
                </li>
              ))}
            </ul>
          ) : (
            <p className="gen-note">
              Waiting for the approved pipeline to reach this agent.
            </p>
          )}
        </div>
      )}
    </aside>
  );
}
export function RequirementLinks({ ids }: { ids: readonly string[] }) {
  return (
    <div className="gen-requirement-links">
      {ids.map((id) => (
        <Link key={id} to={`/requirements?selected=${id}`}>
          {id} ↗
        </Link>
      ))}
    </div>
  );
}
